a few nix toolchain update according to buck2 change. nixified GHC bootstrap not working yet.
This turns out that the new fix for hs-boot is relevant, and we should not
assume boostrap GHC has that patch. (as stage0 compiler)

we need to have correct stage1 compilation
(using nixified-GHC and nixified dependencies as stage0)

$ buck2 build //ghc-build:ghc-bignum
File changed: root//
Build ID: d5083f43-1e18-4650-84db-dc4087749e6c
Jobs completed: 3. Time elapsed: 0.0s.
BUILD FAILED
Traceback (most recent call last):
  File <builtin>, in <module>
  * prelude/haskell/compile.bzl:751, in _dynamic_do_compile_impl
      for module_name in post_order_traversal(graph):
error: Key `"GHC.Num.BigNat-boot"` was not found
  --> prelude/utils/graph_utils.bzl:60:13
   |
60 |             rdeps[dep].append(node)
   |             ^^^^^^^^^^
   |