try linux rts build.
currently fail at link step due to StgRun.

Schedule.c:(.text+0xc51): undefined reference to `StgRun'
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: buck-out/v2/gen/root/904931f735703749/ghc-build/__rts__/libghc-build_rts.so: hidden symbol `StgRun' isn't defined